---

- name: 'Get current nginx version'
  shell: nginx -v 2>&1 | awk -F/ '{print $2}'
  register: nginx_current_version_output
  changed_when: false
  ignore_errors: true

- name: Set proper nginx version
  set_fact:
    nginx_current_version: "{{ nginx_current_version_output.stdout | default('0.0.0') }}"

- name: show version
  debug:
    msg: '{{ nginx_current_version }}'

- name: Install nginx
  include: install.yml
  tags: ['nginx-install']

- name: Install GeoIP
  include: geoip.yml
  when: install_geoip
  tags: ['nginx-geoip']

- name: Install ssl certificates
  include: ssl.yml
  tags: ['nginx-ssl']

- name: Generate dhparam.pem
  include: dhparam.yml
  tags: ['nginx-dhparam']

- name: Configure vhosts
  include: vhosts.yml
  tags: ['nginx-vhosts']

- name: Start nginx
  service:
    name: 'nginx'
    state: started
    enabled: yes
