
# Install nginx
- name: Install nginx
  apt: name={{ item }} state=present
  with_items: nginx_package

- name: Verify nginx service
  service: name=nginx state=started

# Configure nginx
- name: Make sure folders are present
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items: nginx_folders_required

- name: Copy main configurations
  template:
    src: "{{ item }}"
    dest: "/etc/nginx/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  with_items: "{{ nginx_default_config_files + nginx_config_files }}"