
# Install nginx
- name: Install nginx
  action: apt name={{ item }} state=present
  with_items: nginx_package

- name: Verify nginx service
  action: service name=nginx state=started

# Configure nginx
- name: Make sure folders are present
  file: path={{ item }} state=directory
  with_items:
    - /etc/nginx/
    - /etc/nginx/conf.d/

- name: Copy main configurations
  template: src={{ item }} dest=/etc/nginx/ owner={{ nginx_owner }} group={{ nginx_group }} mode=0644
  notify: restart nginx
  with_items:
    - nginx.conf

- name: Copy conf.d/ configurations
  template: src=conf.d/{{ item }} dest=/etc/nginx/conf.d/ owner={{ nginx_owner }} group={{ nginx_group }} mode=0644
  notify: restart nginx
  with_items:
    - cache.conf
    - fastcgi.conf
    - gzip.conf
    - logging.conf
    - mail.conf
    - ssl.conf
